### ISSUE TITLE
Symbolicons vs Symbolicons font

### ISSUE THREAD

**Issue by andreweick** [andreweick/aedc2#15]
Right now I have the symbol icons loading as a font -- is it better (in terms of download size?) to use the specific images for the handful of images I'm actually using?

**Comment by joshuaogle** [comment]
Using images you'd have to include either a retina and non-retina version or use the svg fallback I've included and use an svg + png (non-retina) fallback. That ends up being slower since it's another request and the png versions are a lot bigger. The font uses the same amount of code as the svg would, but not having another server request and the increased browser support is really nice.

I wouldn't let size be the determining factor though. With as few as you have, I would use the svg/png method. Most browsers will only grab the svg, and with as few images as we're using the extra request isn't that big of a deal. For an example of how to mix the font icons and a custom image, look at the App.net icon I have included on the About page.
